/*
 * S_SEG.c

 *
 *  Created on: ???/???/????
 *      Author: dell
 */
#include "S_SEG_CFG.h"
#include "DIO.h"
#define F_CPU 8000000UL
#include <util/delay.h>

void S_SEG_INIT()
{
	DIO_PORT_DIRECTION(S_SEG_PORT,0xff);
	DIO_PIN_DIRECTION(S_SEG_1_EN_PORT,S_SEG_1_EN_PIN,OUTPUT);
	DIO_PIN_DIRECTION(S_SEG_2_EN_PORT,S_SEG_2_EN_PIN,OUTPUT);

}


void S_SEG_WRITE_DIGIT(u8 digit)
{
	switch(digit)
	{
	case 0 :
		DIO_PIN_WRITE(S_SEG_PORT,0,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,1,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,2,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,3,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,4,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,5,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,6,LOW);
		break;
	case 1 :
		DIO_PIN_WRITE(S_SEG_PORT,0,LOW);
		DIO_PIN_WRITE(S_SEG_PORT,1,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,2,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,3,LOW);
		DIO_PIN_WRITE(S_SEG_PORT,4,LOW);
		DIO_PIN_WRITE(S_SEG_PORT,5,LOW);
		DIO_PIN_WRITE(S_SEG_PORT,6,LOW);
		break;
	case 2 :
		DIO_PIN_WRITE(S_SEG_PORT,0,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,1,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,2,LOW);
		DIO_PIN_WRITE(S_SEG_PORT,3,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,4,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,5,LOW);
		DIO_PIN_WRITE(S_SEG_PORT,6,HIGH);
		break;
	case 3 :
		DIO_PIN_WRITE(S_SEG_PORT,0,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,1,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,2,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,3,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,4,LOW);
		DIO_PIN_WRITE(S_SEG_PORT,5,LOW);
		DIO_PIN_WRITE(S_SEG_PORT,6,HIGH);
		break;
	case 4 :
		DIO_PIN_WRITE(S_SEG_PORT,0,LOW);
		DIO_PIN_WRITE(S_SEG_PORT,1,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,2,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,3,LOW);
		DIO_PIN_WRITE(S_SEG_PORT,4,LOW);
		DIO_PIN_WRITE(S_SEG_PORT,5,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,6,HIGH);
		break;
	case 5 :
		DIO_PIN_WRITE(S_SEG_PORT,0,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,1,LOW);
		DIO_PIN_WRITE(S_SEG_PORT,2,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,3,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,4,LOW);
		DIO_PIN_WRITE(S_SEG_PORT,5,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,6,HIGH);
		break;
	case 6 :
		DIO_PIN_WRITE(S_SEG_PORT,0,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,1,LOW);
		DIO_PIN_WRITE(S_SEG_PORT,2,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,3,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,4,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,5,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,6,HIGH);
		break;
	case 7 :
		DIO_PIN_WRITE(S_SEG_PORT,0,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,1,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,2,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,3,LOW);
		DIO_PIN_WRITE(S_SEG_PORT,4,LOW);
		DIO_PIN_WRITE(S_SEG_PORT,5,LOW);
		DIO_PIN_WRITE(S_SEG_PORT,6,LOW);
		break;
	case 8 :
		DIO_PIN_WRITE(S_SEG_PORT,0,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,1,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,2,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,3,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,4,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,5,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,6,HIGH);
		break;
	case 9 :
		DIO_PIN_WRITE(S_SEG_PORT,0,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,1,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,2,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,3,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,4,LOW);
		DIO_PIN_WRITE(S_SEG_PORT,5,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,6,HIGH);
		break;
	}
}



void S_SEG_WRITE_INT(u8 num)
{

	u8 l_num = num / 10;
	u8 r_num = num % 10;

	DIO_PIN_WRITE(S_SEG_1_EN_PORT,S_SEG_1_EN_PIN,HIGH);
	DIO_PIN_WRITE(S_SEG_2_EN_PORT,S_SEG_2_EN_PIN,LOW);

	switch(l_num)
	{
	case 0 :
		DIO_PIN_WRITE(S_SEG_PORT,0,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,1,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,2,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,3,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,4,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,5,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,6,LOW);
		break;
	case 1 :
		DIO_PIN_WRITE(S_SEG_PORT,0,LOW);
		DIO_PIN_WRITE(S_SEG_PORT,1,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,2,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,3,LOW);
		DIO_PIN_WRITE(S_SEG_PORT,4,LOW);
		DIO_PIN_WRITE(S_SEG_PORT,5,LOW);
		DIO_PIN_WRITE(S_SEG_PORT,6,LOW);
		break;
	case 2 :
		DIO_PIN_WRITE(S_SEG_PORT,0,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,1,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,2,LOW);
		DIO_PIN_WRITE(S_SEG_PORT,3,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,4,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,5,LOW);
		DIO_PIN_WRITE(S_SEG_PORT,6,HIGH);
		break;
	case 3 :
		DIO_PIN_WRITE(S_SEG_PORT,0,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,1,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,2,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,3,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,4,LOW);
		DIO_PIN_WRITE(S_SEG_PORT,5,LOW);
		DIO_PIN_WRITE(S_SEG_PORT,6,HIGH);
		break;
	case 4 :
		DIO_PIN_WRITE(S_SEG_PORT,0,LOW);
		DIO_PIN_WRITE(S_SEG_PORT,1,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,2,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,3,LOW);
		DIO_PIN_WRITE(S_SEG_PORT,4,LOW);
		DIO_PIN_WRITE(S_SEG_PORT,5,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,6,HIGH);
		break;
	case 5 :
		DIO_PIN_WRITE(S_SEG_PORT,0,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,1,LOW);
		DIO_PIN_WRITE(S_SEG_PORT,2,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,3,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,4,LOW);
		DIO_PIN_WRITE(S_SEG_PORT,5,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,6,HIGH);
		break;
	case 6 :
		DIO_PIN_WRITE(S_SEG_PORT,0,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,1,LOW);
		DIO_PIN_WRITE(S_SEG_PORT,2,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,3,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,4,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,5,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,6,HIGH);
		break;
	case 7 :
		DIO_PIN_WRITE(S_SEG_PORT,0,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,1,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,2,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,3,LOW);
		DIO_PIN_WRITE(S_SEG_PORT,4,LOW);
		DIO_PIN_WRITE(S_SEG_PORT,5,LOW);
		DIO_PIN_WRITE(S_SEG_PORT,6,LOW);
		break;
	case 8 :
		DIO_PIN_WRITE(S_SEG_PORT,0,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,1,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,2,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,3,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,4,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,5,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,6,HIGH);
		break;
	case 9 :
		DIO_PIN_WRITE(S_SEG_PORT,0,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,1,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,2,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,3,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,4,LOW);
		DIO_PIN_WRITE(S_SEG_PORT,5,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,6,HIGH);
		break;
	}
	_delay_ms(5);
	DIO_PIN_WRITE(S_SEG_1_EN_PORT,S_SEG_1_EN_PIN,LOW);
	DIO_PIN_WRITE(S_SEG_2_EN_PORT,S_SEG_2_EN_PIN,HIGH);
	switch(r_num)
	{
	case 0 :
		DIO_PIN_WRITE(S_SEG_PORT,0,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,1,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,2,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,3,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,4,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,5,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,6,LOW);
		break;
	case 1 :
		DIO_PIN_WRITE(S_SEG_PORT,0,LOW);
		DIO_PIN_WRITE(S_SEG_PORT,1,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,2,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,3,LOW);
		DIO_PIN_WRITE(S_SEG_PORT,4,LOW);
		DIO_PIN_WRITE(S_SEG_PORT,5,LOW);
		DIO_PIN_WRITE(S_SEG_PORT,6,LOW);
		break;
	case 2 :
		DIO_PIN_WRITE(S_SEG_PORT,0,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,1,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,2,LOW);
		DIO_PIN_WRITE(S_SEG_PORT,3,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,4,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,5,LOW);
		DIO_PIN_WRITE(S_SEG_PORT,6,HIGH);
		break;
	case 3 :
		DIO_PIN_WRITE(S_SEG_PORT,0,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,1,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,2,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,3,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,4,LOW);
		DIO_PIN_WRITE(S_SEG_PORT,5,LOW);
		DIO_PIN_WRITE(S_SEG_PORT,6,HIGH);
		break;
	case 4 :
		DIO_PIN_WRITE(S_SEG_PORT,0,LOW);
		DIO_PIN_WRITE(S_SEG_PORT,1,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,2,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,3,LOW);
		DIO_PIN_WRITE(S_SEG_PORT,4,LOW);
		DIO_PIN_WRITE(S_SEG_PORT,5,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,6,HIGH);
		break;
	case 5 :
		DIO_PIN_WRITE(S_SEG_PORT,0,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,1,LOW);
		DIO_PIN_WRITE(S_SEG_PORT,2,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,3,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,4,LOW);
		DIO_PIN_WRITE(S_SEG_PORT,5,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,6,HIGH);
		break;
	case 6 :
		DIO_PIN_WRITE(S_SEG_PORT,0,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,1,LOW);
		DIO_PIN_WRITE(S_SEG_PORT,2,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,3,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,4,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,5,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,6,HIGH);
		break;
	case 7 :
		DIO_PIN_WRITE(S_SEG_PORT,0,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,1,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,2,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,3,LOW);
		DIO_PIN_WRITE(S_SEG_PORT,4,LOW);
		DIO_PIN_WRITE(S_SEG_PORT,5,LOW);
		DIO_PIN_WRITE(S_SEG_PORT,6,LOW);
		break;
	case 8 :
		DIO_PIN_WRITE(S_SEG_PORT,0,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,1,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,2,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,3,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,4,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,5,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,6,HIGH);
		break;
	case 9 :
		DIO_PIN_WRITE(S_SEG_PORT,0,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,1,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,2,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,3,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,4,LOW);
		DIO_PIN_WRITE(S_SEG_PORT,5,HIGH);
		DIO_PIN_WRITE(S_SEG_PORT,6,HIGH);
		break;
	}
	_delay_ms(5);
	DIO_PIN_WRITE(S_SEG_2_EN_PORT,S_SEG_2_EN_PIN,LOW);


}



void Count_Down(u8 num)
{
	while(num >= 0)
		S_SEG_WRITE_INT(num--);
}
